### ISSUE TITLE
startup problems......

### ISSUE THREAD

**Issue by bwired-nl** [rfxcom/node-rfxcom#27]
Hi Kevin
If I start the nodejs in 30% of the cases i get below
if i stop and start again after this it works always on second start
do you see this also sometimes, or only in my case
thnaks Pieter

pi@raspberrypi ~ $ node testrfx                                                                             Sent    : 0D,00,00,00,00,00,00,00,00,00,00,00,00,00
Sent    : 0D,00,00,01,02,00,00,00,00,00,00,00,00,00
Device initialised
Received: 00
Unhandled packet type = 00
Received: 00
Unhandled packet type = 00
Received: 00
Unhandled packet type = 00
Received: 00
Unhandled packet type = 00
Received: 00
Unhandled packet type = 00
Received: 00
Unhandled packet type = 00
Received: 00
Unhandled packet type = 00
Received: 00
Unhandled packet type = 00
Received: 00
Unhandled packet type = 00
Received: 00
Unhandled packet type = 00

**Comment by maxwellhadley** [comment]
I believe version 0.8.0 should have eliminated this issue. I think it occurred when data was sent to the RFXtrx in the first 5 seconds after it powers up: this causes it to enter the flash boot loader.

**Comment by maxwellhadley** [comment]
Another user has reported to me seeing this issue recurring, and provided logs. The main problem is that the parser can lose synchronisation, as discussed above, but also an unhanded exception can occur in a packet handler which gets called with too short a message. The underlying problem is that the parser does not handle buffers which contain more than one message (or parts of more than one message) correctly. This happened on a heavily-loaded Raspberry Pi, running NodeJS 0.10.29
